routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use App\User;
use \App\Mentor;
use \App\Discount;
/**
 * Main Website ROUTE
 */
Route::get('/', 'LandingPageController@index')->name('landingpage');
Route::post('/search-mentor', 'LandingPageController@searchMentor')->name('search.mentor');
Route::get('/about-us', 'AboutController@index')->name('about-us');
Route::get('/faq', 'AboutController@faqIndex')->name('about-us');
Route::get('/dummy/mentor', 'DummyController@index')->name('dummymentor');
Route::get('/dummy/mentor/show', 'DummyController@view')->name('dummymentorshow');
Route::get('/notification', 'UserController@indexAllNotification')->name('indexAllNotification');
Route::post('/cart/submit-donation', 'CartController@submitDonation')->name('carts.submitDonation');
Route::post('/paymentnotification/handler', 'CartController@notificationHandler')->name('notification.handler');
Route::get('/search', 'LessonController@search')->name('search');
Route::get('/cart', 'CartController@index')->name('indexAllPurchases')->middleware('auth');
Route::get('/faq', 'FaqController@index')->name('faq');
Route::get('/faq/{id}/read', 'FaqController@detail')->name('faq-detail');
Route::get('/privacy-policies', 'SupportDeskController@privacyPolicyPage')->name('privacyPolicies');
Route::get('/privacy-policy/{id}/read', 'SupportDeskController@privacyPolicyDetail')->name('privacyDetail');
Route::get('/terms-and-conditions', 'SupportDeskController@termsAndConditionsPage')->name('termsAndConditions');
Route::get('/terms-and-condition/{id}/read', 'SupportDeskController@termsAndConditionDetail')->name('termsDetail');
Route::resource('news','NewsController')->only(['index', 'showFrontend']);
Route::resource('mentors','MentorController')->only(['index', 'show']);
Route::resource('freecourse','FreecourseController')->only(['show']);
Route::get('/news', 'NewsController@indexFrontend')->name('newsFrontend');
Route::get('/news/{id}/read', 'NewsController@readNewsDetail')->name('readNewsFrontend');
Route::group(['middleware' => 'auth'], function () {
    Route::resource('carts', 'CartController');
    Route::get('/v1/cart/clear-all', 'CartController@clearAll')->name('cart.clearall');
    Route::resource('wishlists', 'WishlistController');
    Route::get('/wishlists/{id}/remove', 'WishlistController@remove')->name('wishlists.remove');
    Route::post('/cart/checkout', 'CartController@checkout')->name('cart.checkout')->middleware('verified');

    Route::post('/transaction-success', function () {
        return view('website.transactionsuccess');
    })->name('cart.finish');
    Route::post('/transaction-pending', function () {
        return view('website.transactionpending');
    })->name('cart.pending');
    Route::post('/transaction-failed', function () {
      return view('website.transactionfailed');
    })->name('cart.failed');;
});
Route::post('news/search', 'NewsController@search')->name('news.search');
Route::get('/certificate', 'UserController@certificate')->name('certificate');
Route::group(['as' => 'main.', 'middleware' => ['auth']], function(){
//    Route::get('/redirect', 'SocialAuthGoogleController@redirect')->name('redirect');
//    Route::get('/home', 'HomeController@index')->name('home');
//    Route::get('/mentors/{mid}/lessons/{lid}', 'LessonController@show')->middleware(['can_watch_lesson']);

//    Route::resource('mentors.lessons','MentorLessonController')->middleware(['can_watch_lesson'])->only(['show']);
//    Route::resource('comments','CommentController');
    Route::post('/mentor/{username}/send-rating', 'MentorController@sendRating')->name('mentor.send-rating');
    Route::post('/lesson/enroll/{username}','LessonController@enroll')->name('comment.enroll');
    Route::get('/profile/{username}', 'UserController@show')->name('user.profile');
    Route::post('/profile/{id}', 'UserController@update')->name('user.profile.update');
    Route::put('/profile/update-password', 'UserController@updatePassword')->name('user.profile.update-password');
    Route::get('/profile/{username}/my-course', 'UserController@myCourses')->name('user.my-courses');
    Route::get('/quiz', function() {
      return view('website.quiz');
    })->name('quiz');
    Route::group(['middleware' => ['auth','can_watch_lesson']], function() {
//        Route::get('/mentors/{mid}/lessons/{lid}', 'LessonController@show');
        Route::resource('mentors.lessons','MentorLessonController')->only(['show'])->middleware('verified');
        Route::get('/mentors/{mentor}/lessons/{lesson}/fetch-comment', 'MentorLessonController@fetchComment')->name('mentors.lessons.fetch-comment');
        Route::post('/mentors/{mentor}/lessons/{lesson}/send-comment', 'MentorLessonController@sendComment')->name('mentors.lessons.send-comment');
        Route::post('/mentors/{mentor}/lessons/{lesson}/edit-comment', 'MentorLessonController@editComment')->name('mentors.lessons.edit-comment');
        Route::post('/mentors/{mentor}/lessons/{lesson}/delete-comment', 'MentorLessonController@deleteComment')->name('mentors.lessons.delete-comment');
        Route::post('/mentors/{mentor}/lessons/{lesson}/finish-watching', 'MentorLessonController@finishWatching')->name('mentors.lessons.finish-watching');
    });

    Route::get('/pay/snaptoken', 'SnapController@token')->name('midtrans.snap');
    Route::post('/pay/payment-summary', 'SnapController@finish')->name('midtrans.finish');
});
Route::post('/pay/notification', 'SnapController@notification');


/**
 * ADMIN ROUTE
*/
Route::group(['prefix' => 'adm', 'middleware' => ['auth','role:admin|mentor|staff']], function(){
    Route::get('/', function() { return redirect()->route('mentors.index'); } );
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::get('/setting', 'SettingController@index')->name('setting.index');
    Route::get('/setting/landingpage', 'SettingController@landingpage')->name('setting.landingpage');
    Route::put('/setting/landingpage', 'SettingController@updateLandingpage')->name('setting.landingpage.update');
    Route::resource('mentors.lessons','MentorLessonController');
    Route::post('/mentors/{username}/lesson/upload-video', 'MentorLessonController@upload')->name('lessons.upload-video');
    Route::group(['middleware' => ['role:admin']],function (){
        Route::resource('users','UserController');
        Route::resource('freecourses','FreecourseController');
        Route::resource('news','NewsController');
        Route::resource('faq', 'FaqController');
        Route::resource('support', 'SupportDeskController');
        Route::resource('discounts','DiscountController');
        Route::get('/discounts/{did}/assign', 'DiscountController@viewAssign')->name('discounts.view-assign');
        Route::post('/discounts/{did}/assign', 'DiscountController@doAssign')->name('discounts.do-assign');

    });
    Route::group(['middleware' => ['role:admin|staff']],function (){
        Route::resource('mentors','MentorController');
        Route::post('/mentors/{mentor}/rearrange', 'MentorController@rearrangeLesson')->name('mentors.rearrange');
        Route::post('/mentors/{mentor}/select-review', 'MentorController@selectReview')->name('mentors.select-review');

        Route::resource('lessons','LessonController');
    });
    Route::group(['middleware' => ['role:admin|mentor']],function (){
        Route::resource('mentors','MentorController')->only(['show', 'edit','update']);
    });
});

/**
 * AUTHENICATION ROUTE
 */
Auth::routes(['verify' => true]);
Route::get('/redirect', 'SocialAuthGoogleController@redirect')->name('redirect');
Route::get('/callback', 'SocialAuthGoogleController@callback')->name('callback');










/*
 * Route Dibawah hanya Untuk kebutuhan Dev Saja
 * Nanti Akan Dihapus.
 * "Ikhsn"
 */

Route::get('/create-new-roles', function() {
    DB::transaction(function () {
        $permission = Permission::create(['name' => 'read comments']);

        $role = Role::create(['name' => 'student']);
        $role->givePermissionTo($permission);
        Role::create(['name' => 'super-admin']);
        Role::create(['name' => 'admin']);
        Role::create(['name' => 'staff']);
        Role::create(['name' => 'mentors']);
    });
});

Route::get('/give-permission-to', function() {
    $role = Role::where('name','super-admin')->first();
    $permission = Permission::all();
    DB::transaction(function () use ($role, $permission){
        $role->givePermissionTo($permission);
    });
});

Route::get('/generate-user',function (){
    DB::beginTransaction();
    try {
        // $permission = Permission::create(['name' => 'read comments']);

        $roleSuperadmin = Role::create(['name' => 'super-admin']);
        $roleAdmin = Role::create(['name' => 'admin']);
        $roleStaff = Role::create(['name' => 'staff']);
        $roleMentor = Role::create(['name' => 'mentor']);
        $roleStudent = Role::create(['name' => 'student']);
        // $roleStudent->givePermissionTo($permission);

        $superadmin = new User([
            'name' => 'super admin',
            'username' => 'superadmin',
            'email' => 'superadmin@gmail.com',
            'password' => bcrypt('password'),
        ]);
        $superadmin->save();
        $superadmin->assignRole($roleSuperadmin);

        $admin = new User([
            'name' => 'first admin',
            'username' => 'firstadmin',
            'email' => 'firstadmin@gmail.com',
            'password' => bcrypt('password'),
        ]);

        $admin->save();
        $admin->assignRole($roleAdmin);

app/Lesson.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Illuminate\Database\Eloquent\SoftDeletes;

class Lesson extends Model implements hasMedia
{
    use HasMediaTrait;
    use SoftDeletes;
    const LESSON_MEDIA_TYPE_VIDEO = 'lesson-video';
    const LESSON_MEDIA_THUMBNAIL = 'thumbnail-photo';

    public static $createRules = [
        'title' => 'required|max:255',
        'slug' => 'required|alpha_dash|unique:lessons,slug,NULL,id,deleted_at,NULL',
        'desc' => 'required',
        'thumbnail_photo' => 'required|image',
        'lesson_video_dacast_id' => 'required',
        'duration' => 'required',
//        'lesson_video_url' => 'required',
//        'lesson_video' => 'required|mimetypes:video/x-flv,video/mp4,video/quicktime,video/x-msvideo,video/x-ms-wmv',
    ];
    public static $updateRules = [
        'title' => 'required|max:255',
        'slug' => 'required|alpha_dash|unique:lessons,slug',
        'desc' => 'required',
        'thumbnail_photo' => 'image',
        'lesson_video_dacast_id' => 'required',
        'duration' => 'required',
//        'lesson_video_url' => 'required',
//        'lesson_video' => 'required|mimetypes:video/x-flv,video/mp4,video/quicktime,video/x-msvideo,video/x-ms-wmv',
    ];

    public function mentor() {
        return $this->belongsTo(Mentor::class,'mentor_id');
    }

    public function comments()
    {
        return $this->morphMany(Comment::class, 'commentable');
    }
    public function transactionDetails()
    {
        return $this->morphMany(TransactionDetail::class, 'transactionable');
    }

    public function wishlists () {
      return $this->morphMany(Wishlist::class, 'wishable');
    }

    public function registerMediaCollections()
    {
        $this
            ->addMediaCollection(self::LESSON_MEDIA_THUMBNAIL)
            ->singleFile();
        $this
            ->addMediaCollection(self::LESSON_MEDIA_TYPE_VIDEO)
            ->singleFile();
    }

}

app/Http/Controllers/LessonController.php
<?php

namespace App\Http\Controllers;

use App\Comment;
use App\Lesson;
use App\Mentor;
use App\UserLesson;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class LessonController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if ($this->isAdminPage()) {
            return view('admin.lesson.list');
        }
        return view('website.lessons');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Lesson  $lesson
     * @return \Illuminate\Http\Response
     */
    public function show(Mentor $mentor, Lesson $lesson)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Lesson  $lesson
     * @return \Illuminate\Http\Response
     */
    public function edit(Lesson $lesson)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Lesson  $lesson
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Lesson $lesson)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Lesson  $lesson
     * @return \Illuminate\Http\Response
     */
    public function destroy(Lesson $lesson)
    {
        //
    }

    // search

    public function search() {
      return view('website.search');
    }

    public function sendComment(Request $request,$username)
    {
        $mentor = Mentor::getMentorByUsername($username);
        $request['user_id'] = Auth::id();
        $validatedData = $request->validate(Comment::$createRules);

        // prevent comment 1 menit sekali

        $comment = Comment::findOrNew($request->comment_id);
        $comment->user_id = $validatedData['user_id'];
        $comment->parent_id = $validatedData['parent_id'];
        $comment->text = $validatedData['text'];

        DB::transaction(function () use ($comment, $mentor, $request){
            $comment->save();
            $mentor->comments()->save($comment);

            // Send Notification
            // Send to mentor and parent comment owner

            echo json_encode(['status' => 'success', 'msg' => "Successfully ". $request->comment_id == 0 ? 'send' : 'update' ." comment"]); die();
        });
    }

    public function enroll(Request $request, $username){
        $mentor = Mentor::getMentorByUsername($username);
        $lessons = $mentor->lessons();
        $user = Auth::user();
        foreach ($lessons as $lesson){
            $userLesson = UserLesson::where('user_id',$user->id)->find();
            $currentDate = date('Y-m-d H:i:s');
            if (empty($userLesson)){
                $userLesson = new UserLesson();
                $userLesson->last_watch_tm = time();
            }else{
                $currentDate = $userLesson->expired_dt > $currentDate ? $userLesson->expired_dt : $currentDate;
            }
            $days = 30;
            $userLesson->user_id = $user->id;
            $userLesson->buy_count++;
            $userLesson->expired_dt = date("Y-m-d H:i:s", strtotime($currentDate." +".$days." days"));
            $userLesson = 1;

        }
    }
}

resources/views/admin/lesson/create.blade.php
@extends('layouts.admin')
@section('title','Lessons')
@section('subTitle','Lesson')
@section('style')
    <!-- Select2 -->
    <link rel="stylesheet" href="{{ asset('plugins/select2/css/select2.min.css') }}">
    <link rel="stylesheet" href="{{ asset('plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.7.0/min/dropzone.min.css">
    <link rel="stylesheet" href="{{ asset('plugins/bootstrap-duration-picker/bootstrap-duration-picker.css') }}">
@endsection
@section('breadcrumb')
    <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href="{{ route('mentors.index') }}">Mentors</a></li>
        <li class="breadcrumb-item"><a href="{{ route('mentors.show',$mentor->user->username) }}">Profile</a></li>
        <li class="breadcrumb-item active">Add Lesson</li>
    </ol>
@endsection
@section('content')

    <form action="{{ route('mentors.lessons.store',$mentor->user->username) }}" method="post" enctype="multipart/form-data" >
        @csrf
        <div class="row">
            <div class="col-12">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <h5><i class="fas fa-exclamation-triangle"></i> Error:</h5>
                        <ul class="m-1 pl-3">
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card card-success card-outline">
                    <!-- /.card-header -->
                    <div class="card-body">
                        <div class="form-group">
                            <label for="txtTitle">Title</label>
                            <input id="txtTitle" type="text" name="title" value="{{ old('title') }}" class="form-control @error('title') is-invalid @enderror" placeholder="Enter Title" >
                            @error('title')
                            <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="txtSlug">Slug</label>
                            <input id="txtSlug" type="text" name="slug" value="{{ old('slug') }}" class="form-control @error('slug') is-invalid @enderror" placeholder="Customize Slug" >
                            @error('slug')
                            <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                            @enderror
                        </div>

                        <div class="form-group">
                            <label for="txtDesc">Description</label>
                            <textarea id="txtDesc" name="desc" class="form-control @error('desc') is-invalid @enderror" rows="3" placeholder="Enter ..." >{{ old('desc') }}</textarea>
                            @error('desc')
                            <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                            @enderror
                        </div>

                        <div class="form-group">
                            <label for="inpThumbnailPhoto">Thumbnail Photo <small>(.jpg, .jpeg, .png)</small></label>
                            <div class="custom-file">
                                <input value="{{ old('thumbnail_photo') }}" name="thumbnail_photo" type="file" class="custom-file-input @error('thumbnail_photo') is-invalid @enderror" id="inpThumbnailPhoto" accept="image/*"  >
                                <label class="custom-file-label" for="inpThumbnailPhoto">Choose file...</label>
                                @error('thumbnail_photo')
                                <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="txtLessonVideoURL">Lesson Video Dacast ID</label>
                            <input id="txtLessonVideoURL" type="text" name="lesson_video_dacast_id" value="{{ old('lesson_video_dacast_id') }}" class="form-control @error('lesson_video_dacast_id') is-invalid @enderror" placeholder="Enter URL" >
                            @error('lesson_video_dacast_id')
                            <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                            @enderror
                        </div>

                        <div class="form-group">
                            <label for="txtDuration">Duration</label>
                            <input id="txtDuration" type="text" name="duration" value="{{ old('duration') }}" class="form-control bs-duration-picker @error('duration') is-invalid @enderror" placeholder="Enter duration" >
                            @error('duration')
                            <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                            @enderror
                        </div>
                        {{-- <div class="form-group">
                            <label for="inpHighlightVideo">Lesson Video <small>(.flv, .mp4, .mov, .avi, .wmv)</small></label>
                            <div class="custom-file">
                                <input name="lesson_video" type="file" class="custom-file-input @error('lesson_video') is-invalid @enderror" id="inpLessonVideo" accept="video/*" >
                                <label class="custom-file-label" for="inpLessonVideo">Choose file...</label>
                                @error('lesson_video')
                                <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                                @enderror
                            </div>
                        </div> --}}
                    </div>
                    <!-- /.card-body -->

                </div>
            </div>
        </div>
        <div class="row ">
            <div class="col-12 mb-3">
                <input type="submit" value="Save" class="btn btn-success float-right">
            </div>
        </div>
    </form>

@endsection

@section('script')
<!-- Select2 -->
<script src="{{ asset('plugins/select2/js/select2.full.min.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.7.0/min/dropzone.min.js"></script>
<script src="{{ asset('plugins/bootstrap-duration-picker/bootstrap-duration-picker.js') }}"></script>
<script>
    // A quick way setup
    Dropzone.autoDiscover = false;
    if ($("#my-awesome-dropzone").length > 0) {
        var token = $('input[name=_token]').val();

        // A quick way setup
        var myDropzone = new Dropzone("#my-awesome-dropzone", {
            // Setup chunking
            chunking: true,
            method: "POST",
            maxFilesize: 400000000,
            chunkSize: 1000000,
            // If true, the individual chunks of a file are being uploaded simultaneously.
            parallelChunkUploads: true
        });

        // Append token to the request - required for web routes
        myDropzone.on('sending', function (file, xhr, formData) {
            formData.append("_token", token);
        })
    }
    $('input[type="file"]').change(function(e){
        var fileName = e.target.files[0].name;
        $(this).closest('.form-group').find('.custom-file-label').html(fileName);
    });

    $('.bs-duration-picker').durationPicker({
        showSeconds: true,
        showDays: false,
        onChanged: function (value, isInitializing) {
            console.log(value, isInitializing);
        }
    });
    $('.select2bs4').select2({
        theme: 'bootstrap4'
    })
    $("#txtTitle").on('input',function(){
        var Text = $(this).val();
        // console.log(Text);
        Text = convertToSlug(Text);
        mentorName = "{{$mentor->user->username}}";
        $("#txtSlug").val(mentorName+'-'+Text);
    });
    function convertToSlug(Text)
    {
        return Text
            .toLowerCase()
            .replace(/[^\w ]+/g,'')
            .replace(/ +/g,'-')
            ;
    }
</script>
@endsection

resources/views/admin/lesson/list.blade.php
@extends('layouts.admin')

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">Lessons</div>
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    This is Lessons page
                </div>
            </div>
        </div>
    </div>
@endsection