routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use App\User;
use \App\Mentor;
use \App\Discount;
/**
 * Main Website ROUTE
 */
Route::get('/', 'LandingPageController@index')->name('landingpage');
Route::post('/search-mentor', 'LandingPageController@searchMentor')->name('search.mentor');
Route::get('/about-us', 'AboutController@index')->name('about-us');
Route::get('/faq', 'AboutController@faqIndex')->name('about-us');
Route::get('/dummy/mentor', 'DummyController@index')->name('dummymentor');
Route::get('/dummy/mentor/show', 'DummyController@view')->name('dummymentorshow');
Route::get('/notification', 'UserController@indexAllNotification')->name('indexAllNotification');
Route::post('/cart/submit-donation', 'CartController@submitDonation')->name('carts.submitDonation');
Route::post('/paymentnotification/handler', 'CartController@notificationHandler')->name('notification.handler');
Route::get('/search', 'LessonController@search')->name('search');
Route::get('/cart', 'CartController@index')->name('indexAllPurchases')->middleware('auth');
Route::get('/faq', 'FaqController@index')->name('faq');
Route::get('/faq/{id}/read', 'FaqController@detail')->name('faq-detail');
Route::get('/privacy-policies', 'SupportDeskController@privacyPolicyPage')->name('privacyPolicies');
Route::get('/privacy-policy/{id}/read', 'SupportDeskController@privacyPolicyDetail')->name('privacyDetail');
Route::get('/terms-and-conditions', 'SupportDeskController@termsAndConditionsPage')->name('termsAndConditions');
Route::get('/terms-and-condition/{id}/read', 'SupportDeskController@termsAndConditionDetail')->name('termsDetail');
Route::resource('news','NewsController')->only(['index', 'showFrontend']);
Route::resource('mentors','MentorController')->only(['index', 'show']);
Route::resource('freecourse','FreecourseController')->only(['show']);
Route::get('/news', 'NewsController@indexFrontend')->name('newsFrontend');
Route::get('/news/{id}/read', 'NewsController@readNewsDetail')->name('readNewsFrontend');
Route::group(['middleware' => 'auth'], function () {
    Route::resource('carts', 'CartController');
    Route::get('/v1/cart/clear-all', 'CartController@clearAll')->name('cart.clearall');
    Route::resource('wishlists', 'WishlistController');
    Route::get('/wishlists/{id}/remove', 'WishlistController@remove')->name('wishlists.remove');
    Route::post('/cart/checkout', 'CartController@checkout')->name('cart.checkout')->middleware('verified');

    Route::post('/transaction-success', function () {
        return view('website.transactionsuccess');
    })->name('cart.finish');
    Route::post('/transaction-pending', function () {
        return view('website.transactionpending');
    })->name('cart.pending');
    Route::post('/transaction-failed', function () {
      return view('website.transactionfailed');
    })->name('cart.failed');;
});
Route::post('news/search', 'NewsController@search')->name('news.search');
Route::get('/certificate', 'UserController@certificate')->name('certificate');
Route::group(['as' => 'main.', 'middleware' => ['auth']], function(){
//    Route::get('/redirect', 'SocialAuthGoogleController@redirect')->name('redirect');
//    Route::get('/home', 'HomeController@index')->name('home');
//    Route::get('/mentors/{mid}/lessons/{lid}', 'LessonController@show')->middleware(['can_watch_lesson']);

//    Route::resource('mentors.lessons','MentorLessonController')->middleware(['can_watch_lesson'])->only(['show']);
//    Route::resource('comments','CommentController');
    Route::post('/mentor/{username}/send-rating', 'MentorController@sendRating')->name('mentor.send-rating');
    Route::post('/lesson/enroll/{username}','LessonController@enroll')->name('comment.enroll');
    Route::get('/profile/{username}', 'UserController@show')->name('user.profile');
    Route::post('/profile/{id}', 'UserController@update')->name('user.profile.update');
    Route::put('/profile/update-password', 'UserController@updatePassword')->name('user.profile.update-password');
    Route::get('/profile/{username}/my-course', 'UserController@myCourses')->name('user.my-courses');
    Route::get('/quiz', function() {
      return view('website.quiz');
    })->name('quiz');
    Route::group(['middleware' => ['auth','can_watch_lesson']], function() {
//        Route::get('/mentors/{mid}/lessons/{lid}', 'LessonController@show');
        Route::resource('mentors.lessons','MentorLessonController')->only(['show'])->middleware('verified');
        Route::get('/mentors/{mentor}/lessons/{lesson}/fetch-comment', 'MentorLessonController@fetchComment')->name('mentors.lessons.fetch-comment');
        Route::post('/mentors/{mentor}/lessons/{lesson}/send-comment', 'MentorLessonController@sendComment')->name('mentors.lessons.send-comment');
        Route::post('/mentors/{mentor}/lessons/{lesson}/edit-comment', 'MentorLessonController@editComment')->name('mentors.lessons.edit-comment');
        Route::post('/mentors/{mentor}/lessons/{lesson}/delete-comment', 'MentorLessonController@deleteComment')->name('mentors.lessons.delete-comment');
        Route::post('/mentors/{mentor}/lessons/{lesson}/finish-watching', 'MentorLessonController@finishWatching')->name('mentors.lessons.finish-watching');
    });

    Route::get('/pay/snaptoken', 'SnapController@token')->name('midtrans.snap');
    Route::post('/pay/payment-summary', 'SnapController@finish')->name('midtrans.finish');
});
Route::post('/pay/notification', 'SnapController@notification');


/**
 * ADMIN ROUTE
*/
Route::group(['prefix' => 'adm', 'middleware' => ['auth','role:admin|mentor|staff']], function(){
    Route::get('/', function() { return redirect()->route('mentors.index'); } );
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::get('/setting', 'SettingController@index')->name('setting.index');
    Route::get('/setting/landingpage', 'SettingController@landingpage')->name('setting.landingpage');
    Route::put('/setting/landingpage', 'SettingController@updateLandingpage')->name('setting.landingpage.update');
    Route::resource('mentors.lessons','MentorLessonController');
    Route::post('/mentors/{username}/lesson/upload-video', 'MentorLessonController@upload')->name('lessons.upload-video');
    Route::group(['middleware' => ['role:admin']],function (){
        Route::resource('users','UserController');
        Route::resource('freecourses','FreecourseController');
        Route::resource('news','NewsController');
        Route::resource('faq', 'FaqController');
        Route::resource('support', 'SupportDeskController');
        Route::resource('discounts','DiscountController');
        Route::get('/discounts/{did}/assign', 'DiscountController@viewAssign')->name('discounts.view-assign');
        Route::post('/discounts/{did}/assign', 'DiscountController@doAssign')->name('discounts.do-assign');

    });
    Route::group(['middleware' => ['role:admin|staff']],function (){
        Route::resource('mentors','MentorController');
        Route::post('/mentors/{mentor}/rearrange', 'MentorController@rearrangeLesson')->name('mentors.rearrange');
        Route::post('/mentors/{mentor}/select-review', 'MentorController@selectReview')->name('mentors.select-review');

        Route::resource('lessons','LessonController');
    });
    Route::group(['middleware' => ['role:admin|mentor']],function (){
        Route::resource('mentors','MentorController')->only(['show', 'edit','update']);
    });
});

/**
 * AUTHENICATION ROUTE
 */
Auth::routes(['verify' => true]);
Route::get('/redirect', 'SocialAuthGoogleController@redirect')->name('redirect');
Route::get('/callback', 'SocialAuthGoogleController@callback')->name('callback');










/*
 * Route Dibawah hanya Untuk kebutuhan Dev Saja
 * Nanti Akan Dihapus.
 * "Ikhsn"
 */

Route::get('/create-new-roles', function() {
    DB::transaction(function () {
        $permission = Permission::create(['name' => 'read comments']);

        $role = Role::create(['name' => 'student']);
        $role->givePermissionTo($permission);
        Role::create(['name' => 'super-admin']);
        Role::create(['name' => 'admin']);
        Role::create(['name' => 'staff']);
        Role::create(['name' => 'mentors']);
    });
});

Route::get('/give-permission-to', function() {
    $role = Role::where('name','super-admin')->first();
    $permission = Permission::all();
    DB::transaction(function () use ($role, $permission){
        $role->givePermissionTo($permission);
    });
});

Route::get('/generate-user',function (){
    DB::beginTransaction();
    try {
        // $permission = Permission::create(['name' => 'read comments']);

        $roleSuperadmin = Role::create(['name' => 'super-admin']);
        $roleAdmin = Role::create(['name' => 'admin']);
        $roleStaff = Role::create(['name' => 'staff']);
        $roleMentor = Role::create(['name' => 'mentor']);
        $roleStudent = Role::create(['name' => 'student']);
        // $roleStudent->givePermissionTo($permission);

        $superadmin = new User([
            'name' => 'super admin',
            'username' => 'superadmin',
            'email' => 'superadmin@gmail.com',
            'password' => bcrypt('password'),
        ]);
        $superadmin->save();
        $superadmin->assignRole($roleSuperadmin);

        $admin = new User([
            'name' => 'first admin',
            'username' => 'firstadmin',
            'email' => 'firstadmin@gmail.com',
            'password' => bcrypt('password'),
        ]);

        $admin->save();
        $admin->assignRole($roleAdmin);

app/Mentor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\DB;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;

class Mentor extends Model implements HasMedia
{
    use HasMediaTrait;
    use SoftDeletes;

    public $timestamps = true;
    protected $primaryKey = 'mentor_id';
    public $incrementing = false;
    protected $fillable = ['mentor_id', 'primary_p_id', 'highlight_v_id', 'profesi', 'desc', 'price', 'description_p_id', 'visit_count'];
    protected $with = ['user'];
    public $username;

    public static $createRules = [
        'name' => 'required|max:255',
        'username' => 'required|unique:users|max:255',
        'email' => 'required|email|unique:users|max:255',
        'password' => 'required|max:255',
        'confirm_password' => 'required|same:password',
        'gender' => 'required',
        'price' => 'required|numeric',
        'profesi' => 'required|max:50',
        'department' => 'required|max:50',
        'desc' => 'required',
        'avatar_photo' => 'image',
        'primary_photo' => 'required|image',
        'description_photo' => 'image',
        'mentor_video_url' => 'required',
        // 'highlight_video' => 'mimetypes:video/x-flv,video/mp4,video/quicktime,video/x-msvideo,video/x-ms-wmv|max:10000',
    ];

    public static $updateRules = [
        'name' => 'required|max:255',
        'email' => 'sometimes|required|email|unique:users',
        'username' => 'sometimes|required|unique:users',
        'gender' => 'required|numeric',
        'price' => 'required|numeric',
        'profesi' => 'required|max:50',
        'department' => 'required|max:50',
        'desc' => 'required',
        'avatar_photo' => 'image',
        'primary_photo' => 'image',
        'description_photo' => 'image',
        'mentor_video_url' => 'required',
//        'highlight_video' => 'mimetypes:video/x-flv,video/mp4,video/quicktime,video/x-msvideo,video/x-ms-wmv|max:200000',
    ];

    public function user()
    {
        return $this->belongsTo('App\User','mentor_id');
    }
    public function lessons()
    {
        return $this->hasMany(Lesson::class,'mentor_id','mentor_id');
    }

    public function wishlists () {
        return $this->morphMany(Wishlist::class, 'wishable');
    }

    public function transactionDetails()
    {
        return $this->morphMany(TransactionDetail::class, 'transactionable');
    }

    public static function getMentorByUsername($username){
        return self::whereHas('user', function ($q) use ($username) {
            $q->where('username', '=', $username);
        })->firstOrFail();
    }
    /**
     * Set the polymorphic relation.
     *
     * @return \Illuminate\Database\Eloquent\Relations\MorphMany
     */
    public function media()
    {
        return $this->morphMany(config('medialibrary.media_model'), 'model','model_type','model_id','mentor_id');
    }

    public function registerMediaCollections()
    {
        $this
            ->addMediaCollection('primary-photo')
            ->singleFile();
        $this
            ->addMediaCollection('description-photo')
            ->singleFile();
        $this
            ->addMediaCollection('highlight-video')
            ->singleFile();
    }

    public function getBestRating(){
        return MentorRating::where('mentor_id',$this->mentor_id)->orderBy('rating','desc')->orderBy('created_at','desc')->first();
    }
    public function getAvatar(){
        $user = User::find($this->mentor_id);
        return $user->getFirstMediaUrl('avatar-photo');
    }
    public function getTotalStudent(){
        return count(DB::select("SELECT SUM(student_id) as total
            FROM transactions
            JOIN transaction_details ON transactions.id = transaction_details.transaction_id
            WHERE transaction_details.transactionable_type = ?
            AND transaction_details.transactionable_id = ?
            GROUP BY student_id
        ",[Mentor::class, $this->mentor_id]));
    }
    public function discounts(){
        return $this->belongsToMany(Discount::class,'discount_mentor',"mentor_id", "discount_id");
    }

    public function mentor_students(){
        return $this->belongsToMany(StudentMentor::class, 'student_mentors',"mentor_id","student_id");
    }

    public function ratings(){
        return $this->hasMany(MentorRating::class,'mentor_id');
    }

    public function getTotalDuration(){
        return ceil(Lesson::where('mentor_id', $this->mentor_id)->sum('duration') / 60);
    }

    public function getTotalTransaction(){
        return TransactionDetail::where('transactionable_type', Mentor::class)
            ->where('transactionable_id', $this->mentor_id)->count();
    }
}

resources/views/admin/mentor/create.blade.php
@extends('layouts.admin')
@section('title','Mentors')
@section('subTitle','Mentors')
@section('style')
    <!-- Select2 -->
    <link rel="stylesheet" href="{{ asset('plugins/select2/css/select2.min.css') }}">
    <link rel="stylesheet" href="{{ asset('plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}">

@endsection
@section('breadcrumb')
    <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href="{{ route('mentors.index') }}">Mentors</a></li>
        <li class="breadcrumb-item active">Create Mentor</li>
    </ol>
@endsection
@section('content')

    <!-- form start -->
    <form action="{{ route('mentors.store') }}" method="post" enctype="multipart/form-data" >
        @csrf
        <div class="row">
            <div class="col-12">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <h5><i class="fas fa-exclamation-triangle"></i> Error:</h5>
                        <ul class="m-1 pl-3">
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title bold">Profile</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Fullname</label>
                            <input id="txtFullname" type="text" name="name" class="form-control @error('name') is-invalid @enderror" value="{{ old('name') }}" placeholder="Enter Fullname" >
                            @error('name')
                            <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="txtUsername">Username</label>
                            <input id="txtUsername" type="text" name="username" class="form-control @error('username') is-invalid @enderror" value="{{ old('username') }}" placeholder="Enter Username" >
                            @error('username')
                            <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="txtEmail">Email</label>
                            <input id="txtEmail" type="text" name="email" class="form-control @error('email') is-invalid @enderror" value="{{ old('email') }}" placeholder="Enter Username" >
                            @error('email')
                            <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="txtPassword">Password</label>
                            <input id="txtPassword" type="password" name="password" value="{{ old('password') }}" class="form-control @error('password') is-invalid @enderror" placeholder="Password" >
                            @error('password')
                            <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="txtConfirmPassword">Confirm Password</label>
                            <input id="txtConfirmPassword" type="password" name="confirm_password" value="{{ old('password') }}" class="form-control @error('confirm_password') is-invalid @enderror" placeholder="Confirm Password" >
                            @error('confirm_password')
                            <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                            @enderror
                        </div>

                        <div class="form-group">
                            <label>Gender</label>
                            <select name="gender" class="form-control select2bs4 " style="width: 100%;" >

                                @php $genders = [1 => 'Laki-laki', 2 => 'Perempuan'] @endphp
                                @foreach ($genders as $key => $val)
                                    @if (old('gender') == $key)
                                        <option value="{{ $key }}" selected>{{ $val }}</option>
                                    @else
                                        <option value="{{ $key }}">{{ $val }}</option>
                                    @endif
                                @endforeach
                            </select>
                            @error('gender')
                            <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                            @enderror
                        </div>

                    </div>
                    <!-- /.card-body -->

                </div>
            </div>
            <div class="col-md-6">
                <div class="card card-success">
                    <div class="card-header">
                        <h3 class="card-title bold">Mentoring Content</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <div class="form-group">
                            <label for="txtPrice"><b>Price</b></label>
                            <input id="txtPrice" type="numeric" name="price" value="{{ old('price') }}" class="form-control @error('price') is-invalid @enderror border-warning" placeholder="Enter Lesson Price" >
                            @error('price')
                            <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="txtDepartment"><b>Title</b></label>
                            <input id="txtDepartment" type="text" name="department" value="{{ old('department') }}" class="form-control @error('department') is-invalid @enderror border-warning" placeholder="Enter Mentor Title" >
                            @error('department')
                            <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="txtProfesi">Profession</label>
                            <input id="txtProfesi" type="text" name="profesi" value="{{ old('profesi') }}" class="form-control @error('profesi') is-invalid @enderror" placeholder="Enter Profesi" >
                            @error('profesi')
                            <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="txtDesc">Description</label>
                            <textarea id="txtDesc" name="desc" class="form-control @error('desc') is-invalid @enderror" rows="3" placeholder="Enter ..." >{{ old('desc') }}</textarea>
                            @error('desc')
                            <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="inpPrimaryPhoto">Primary Photo <small>(.jpg, .jpeg, .png)</small></label>
                            <div class="custom-file">
                                <input value="{{ old('primary_photo') }}" name="primary_photo" type="file" class="custom-file-input @error('primary_photo') is-invalid @enderror" id="inpPrimaryPhoto" accept="image/*"  >
                                <label class="custom-file-label" for="inpPrimaryPhoto">Choose file...</label>
                                @error('primary_photo')
                                <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="fileDescriptionPhoto">Description Photo <small>(.jpg, .jpeg, .png)</small></label>
                            <div class="custom-file">
                                <input value="{{ old('description_photo') }}" name="description_photo" type="file" class="custom-file-input @error('description_photo') is-invalid @enderror" id="fileDescriptionPhoto" accept="image/*"  >
                                <label class="custom-file-label" for="fileDescriptionPhoto">Choose file...</label>
                                @error('description_photo')
                                <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="txtMentorVideoURL">Highlight Video URL</label>
                            <input id="txtMentorVideoURL" type="text" name="mentor_video_url" value="{{ old('mentor_video_url') }}" class="form-control @error('mentor_video_url') is-invalid @enderror" placeholder="Enter URL" >
                            @error('mentor_video_url')
                            <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                            @enderror
                        </div>
                        {{--
                        <div class="form-group">
                            <label for="inpHighlightVideo">Highlight Video <small>(.flv, .mp4, .mov, .avi, .wmv)</small></label>
                            <div class="custom-file">
                                <input value="{{ old('highlight_video') }}" name="highlight_video" type="file" class="custom-file-input @error('highlight_video') is-invalid @enderror" id="inpHighlightVideo" accept="video/*" >
                                <label class="custom-file-label" for="inpHighlightVideo">Choose file...</label>
                                @error('highlight_video')
                                <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                                @enderror
                            </div>
                        </div>
                        --}}
                    </div>
                    <!-- /.card-body -->

                </div>
            </div>
        </div>
        <div class="row ">
            <div class="col-12 mb-3">
                <input type="submit" value="Create new Mentor" class="btn btn-success float-right">
            </div>
        </div>
    </form>

@endsection

@section('script')
    <!-- Select2 -->
    <script src="{{ asset('plugins/select2/js/select2.full.min.js') }}"></script>

    <script>
        $('input[type="file"]').change(function(e){
            var fileName = e.target.files[0].name;
            $(this).closest('.form-group').find('.custom-file-label').html(fileName);
        });

        $('.select2bs4').select2({
            theme: 'bootstrap4'
        })
    </script>
@endsection

resources/views/admin/mentor/list.blade.php
@extends('layouts.admin')
@section('title','Mentors')
@section('subTitle','Mentors')
@section('style')
    <!-- DataTables -->
    <link rel="stylesheet" href="../../plugins/datatables-bs4/css/dataTables.bootstrap4.css">
@endsection
@section('breadcrumb')
    <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item active">Mentors</li>
    </ol>
@endsection
@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="row mb-2 mb-md-3">
                        <div class="col-12 d-flex justify-content-between">
                            <div class="left"></div>
                            <div class="right">
                                <a class="btn btn-success btn-sm" href="{{ route('mentors.create') }}"> Create Mentor</a>
                            </div>
                        </div>
                    </div>
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <table id="dt1" class="table table-bordered table-hover dt-responsive" width="100%">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Username</th>
                                <th>Email</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($mentors as $mentor)
                                <tr>
                                    <td><a href="{{ route('mentors.show',$mentor->user->username) }}"></a>{{ $mentor->user->name }}</td>
                                    <td>{{ $mentor->user->username }}</td>
                                    <td>{{ $mentor->user->email }}</td>
                                    <td>
                                        <form action="{{ route('mentors.destroy',$mentor->mentor_id) }}" method="POST" style="text-align: right;">

                                            <a class="btn btn-link text-info" href="{{ route('mentors.show',$mentor->user->username) }}"><i class="fas fa-user-tie"></i></a>
                                            <a class="btn btn-link text-primary" href="{{ route('mentors.edit',$mentor->mentor_id) }}"><i class="fas fa-pencil-alt"></i></a>

                                            @csrf
                                            @method('DELETE')

                                            <button type="submit" class="btn btn-link text-danger btnDeleteMentor"><i class="fas fa-trash"></i></button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
<!-- DataTables -->
<script src="{{ asset('plugins/datatables/jquery.dataTables.js') }}"></script>
<script src="{{ asset('plugins/datatables-bs4/js/dataTables.bootstrap4.js') }}"></script>
<script>

    $(function () {
        $('#dt1').DataTable({
            "scrollX": true
        });
    });
    $(document).ready(function () {
        $(".btnDeleteMentor").click(function (e) {
            e.preventDefault();
            if (confirm('Are you sure want to delete this record')) {
                $(this).closest('form').submit();
            } else {
                return false;
            }
        })
    })
</script>
@endsection