routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use App\User;
use \App\Mentor;
use \App\Discount;
/**
 * Main Website ROUTE
 */
Route::get('/', 'LandingPageController@index')->name('landingpage');
Route::post('/search-mentor', 'LandingPageController@searchMentor')->name('search.mentor');
Route::get('/about-us', 'AboutController@index')->name('about-us');
Route::get('/faq', 'AboutController@faqIndex')->name('about-us');
Route::get('/dummy/mentor', 'DummyController@index')->name('dummymentor');
Route::get('/dummy/mentor/show', 'DummyController@view')->name('dummymentorshow');
Route::get('/notification', 'UserController@indexAllNotification')->name('indexAllNotification');
Route::post('/cart/submit-donation', 'CartController@submitDonation')->name('carts.submitDonation');
Route::post('/paymentnotification/handler', 'CartController@notificationHandler')->name('notification.handler');
Route::get('/search', 'LessonController@search')->name('search');
Route::get('/cart', 'CartController@index')->name('indexAllPurchases')->middleware('auth');
Route::get('/faq', 'FaqController@index')->name('faq');
Route::get('/faq/{id}/read', 'FaqController@detail')->name('faq-detail');
Route::get('/privacy-policies', 'SupportDeskController@privacyPolicyPage')->name('privacyPolicies');
Route::get('/privacy-policy/{id}/read', 'SupportDeskController@privacyPolicyDetail')->name('privacyDetail');
Route::get('/terms-and-conditions', 'SupportDeskController@termsAndConditionsPage')->name('termsAndConditions');
Route::get('/terms-and-condition/{id}/read', 'SupportDeskController@termsAndConditionDetail')->name('termsDetail');
Route::resource('news','NewsController')->only(['index', 'showFrontend']);
Route::resource('mentors','MentorController')->only(['index', 'show']);
Route::resource('freecourse','FreecourseController')->only(['show']);
Route::get('/news', 'NewsController@indexFrontend')->name('newsFrontend');
Route::get('/news/{id}/read', 'NewsController@readNewsDetail')->name('readNewsFrontend');
Route::group(['middleware' => 'auth'], function () {
    Route::resource('carts', 'CartController');
    Route::get('/v1/cart/clear-all', 'CartController@clearAll')->name('cart.clearall');
    Route::resource('wishlists', 'WishlistController');
    Route::get('/wishlists/{id}/remove', 'WishlistController@remove')->name('wishlists.remove');
    Route::post('/cart/checkout', 'CartController@checkout')->name('cart.checkout')->middleware('verified');

    Route::post('/transaction-success', function () {
        return view('website.transactionsuccess');
    })->name('cart.finish');
    Route::post('/transaction-pending', function () {
        return view('website.transactionpending');
    })->name('cart.pending');
    Route::post('/transaction-failed', function () {
      return view('website.transactionfailed');
    })->name('cart.failed');;
});
Route::post('news/search', 'NewsController@search')->name('news.search');
Route::get('/certificate', 'UserController@certificate')->name('certificate');
Route::group(['as' => 'main.', 'middleware' => ['auth']], function(){
//    Route::get('/redirect', 'SocialAuthGoogleController@redirect')->name('redirect');
//    Route::get('/home', 'HomeController@index')->name('home');
//    Route::get('/mentors/{mid}/lessons/{lid}', 'LessonController@show')->middleware(['can_watch_lesson']);

//    Route::resource('mentors.lessons','MentorLessonController')->middleware(['can_watch_lesson'])->only(['show']);
//    Route::resource('comments','CommentController');
    Route::post('/mentor/{username}/send-rating', 'MentorController@sendRating')->name('mentor.send-rating');
    Route::post('/lesson/enroll/{username}','LessonController@enroll')->name('comment.enroll');
    Route::get('/profile/{username}', 'UserController@show')->name('user.profile');
    Route::post('/profile/{id}', 'UserController@update')->name('user.profile.update');
    Route::put('/profile/update-password', 'UserController@updatePassword')->name('user.profile.update-password');
    Route::get('/profile/{username}/my-course', 'UserController@myCourses')->name('user.my-courses');
    Route::get('/quiz', function() {
      return view('website.quiz');
    })->name('quiz');
    Route::group(['middleware' => ['auth','can_watch_lesson']], function() {
//        Route::get('/mentors/{mid}/lessons/{lid}', 'LessonController@show');
        Route::resource('mentors.lessons','MentorLessonController')->only(['show'])->middleware('verified');
        Route::get('/mentors/{mentor}/lessons/{lesson}/fetch-comment', 'MentorLessonController@fetchComment')->name('mentors.lessons.fetch-comment');
        Route::post('/mentors/{mentor}/lessons/{lesson}/send-comment', 'MentorLessonController@sendComment')->name('mentors.lessons.send-comment');
        Route::post('/mentors/{mentor}/lessons/{lesson}/edit-comment', 'MentorLessonController@editComment')->name('mentors.lessons.edit-comment');
        Route::post('/mentors/{mentor}/lessons/{lesson}/delete-comment', 'MentorLessonController@deleteComment')->name('mentors.lessons.delete-comment');
        Route::post('/mentors/{mentor}/lessons/{lesson}/finish-watching', 'MentorLessonController@finishWatching')->name('mentors.lessons.finish-watching');
    });

    Route::get('/pay/snaptoken', 'SnapController@token')->name('midtrans.snap');
    Route::post('/pay/payment-summary', 'SnapController@finish')->name('midtrans.finish');
});
Route::post('/pay/notification', 'SnapController@notification');


/**
 * ADMIN ROUTE
*/
Route::group(['prefix' => 'adm', 'middleware' => ['auth','role:admin|mentor|staff']], function(){
    Route::get('/', function() { return redirect()->route('mentors.index'); } );
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::get('/setting', 'SettingController@index')->name('setting.index');
    Route::get('/setting/landingpage', 'SettingController@landingpage')->name('setting.landingpage');
    Route::put('/setting/landingpage', 'SettingController@updateLandingpage')->name('setting.landingpage.update');
    Route::resource('mentors.lessons','MentorLessonController');
    Route::post('/mentors/{username}/lesson/upload-video', 'MentorLessonController@upload')->name('lessons.upload-video');
    Route::group(['middleware' => ['role:admin']],function (){
        Route::resource('users','UserController');
        Route::resource('freecourses','FreecourseController');
        Route::resource('news','NewsController');
        Route::resource('faq', 'FaqController');
        Route::resource('support', 'SupportDeskController');
        Route::resource('discounts','DiscountController');
        Route::get('/discounts/{did}/assign', 'DiscountController@viewAssign')->name('discounts.view-assign');
        Route::post('/discounts/{did}/assign', 'DiscountController@doAssign')->name('discounts.do-assign');

    });
    Route::group(['middleware' => ['role:admin|staff']],function (){
        Route::resource('mentors','MentorController');
        Route::post('/mentors/{mentor}/rearrange', 'MentorController@rearrangeLesson')->name('mentors.rearrange');
        Route::post('/mentors/{mentor}/select-review', 'MentorController@selectReview')->name('mentors.select-review');

        Route::resource('lessons','LessonController');
    });
    Route::group(['middleware' => ['role:admin|mentor']],function (){
        Route::resource('mentors','MentorController')->only(['show', 'edit','update']);
    });
});

/**
 * AUTHENICATION ROUTE
 */
Auth::routes(['verify' => true]);
Route::get('/redirect', 'SocialAuthGoogleController@redirect')->name('redirect');
Route::get('/callback', 'SocialAuthGoogleController@callback')->name('callback');










/*
 * Route Dibawah hanya Untuk kebutuhan Dev Saja
 * Nanti Akan Dihapus.
 * "Ikhsn"
 */

Route::get('/create-new-roles', function() {
    DB::transaction(function () {
        $permission = Permission::create(['name' => 'read comments']);

        $role = Role::create(['name' => 'student']);
        $role->givePermissionTo($permission);
        Role::create(['name' => 'super-admin']);
        Role::create(['name' => 'admin']);
        Role::create(['name' => 'staff']);
        Role::create(['name' => 'mentors']);
    });
});

Route::get('/give-permission-to', function() {
    $role = Role::where('name','super-admin')->first();
    $permission = Permission::all();
    DB::transaction(function () use ($role, $permission){
        $role->givePermissionTo($permission);
    });
});

Route::get('/generate-user',function (){
    DB::beginTransaction();
    try {
        // $permission = Permission::create(['name' => 'read comments']);

        $roleSuperadmin = Role::create(['name' => 'super-admin']);
        $roleAdmin = Role::create(['name' => 'admin']);
        $roleStaff = Role::create(['name' => 'staff']);
        $roleMentor = Role::create(['name' => 'mentor']);
        $roleStudent = Role::create(['name' => 'student']);
        // $roleStudent->givePermissionTo($permission);

        $superadmin = new User([
            'name' => 'super admin',
            'username' => 'superadmin',
            'email' => 'superadmin@gmail.com',
            'password' => bcrypt('password'),
        ]);
        $superadmin->save();
        $superadmin->assignRole($roleSuperadmin);

        $admin = new User([
            'name' => 'first admin',
            'username' => 'firstadmin',
            'email' => 'firstadmin@gmail.com',
            'password' => bcrypt('password'),
        ]);

        $admin->save();
        $admin->assignRole($roleAdmin);

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title>{{ config('app.name', 'Gurusemua') }} - @yield('title')</title>

  <!-- Font Awesome Icons -->
  <link href="{{ asset('plugins/fontawesome-free/css/all.min.css') }}" rel="stylesheet">
  <!-- Theme style -->
  <link href="{{ asset('dist/css/adminlte.min.css') }}" rel="stylesheet">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  {{-- TinyMCE WYSIWYG Editor --}}
  <script src="https://cdn.tiny.cloud/1/eqamb73skytggjqnzutuk6xvkxycl443pbkjiex8garfnhfp/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
  <script src="{{ asset('plugins/jquery/jquery.min.js') }}"></script>
  @yield('style')
</head>
<body class="hold-transition sidebar-mini">
<div id="app" class="wrapper">

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link py-0" data-toggle="dropdown" href="#">
          <div class="image">
            <img src="{{ asset('dist/img/user2-160x160.jpg') }}" class="img-circle elevation-1" alt="User Image" style="width: 2.5rem; height: auto;">
          </div>
        </a>
        <div class="dropdown-menu dropdown-menu-sm dropdown-menu-right">
          <span class="dropdown-header text-capitalize">{{ Auth::user()->name }}</span>
          <div class="dropdown-divider"></div>
          <a href="{{ route('logout') }}" class="dropdown-item" onclick="event.preventDefault();document.getElementById('logout-form').submit();">
            <i class="fas fa-sign-out-alt mr-2"></i> Log out

            <span class="float-right text-muted text-sm"> </span>
          </a>
          <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
            @csrf
          </form>
        </div>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{{ url('/') }}" class="brand-link">
      <img src="{{ asset('img/Logo.png') }}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">Gurusemua</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{{ asset('dist/img/user2-160x160.jpg') }}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">{{ Auth::user()->name }}</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          {{-- <li class="nav-item">
            <a href="{{ route('dashboard') }}" class="nav-link {{ request()->is('adm/dashboard') ? 'active' : ''}}">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Dashboard
                <span class="right badge badge-danger d-none">New</span>
              </p>
            </a>
          </li> --}}
           <li class="nav-item">
            <a href="{{ route('setting.landingpage') }}" class="nav-link {{ request()->is('adm/setting') ? 'active' : ''}}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Landing Page
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ route('mentors.index') }}" class="nav-link {{ request()->is('adm/mentors') ? 'active' : ''}}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Mentors
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ route('freecourses.index') }}" class="nav-link {{ request()->is('adm/freecourses') ? 'active' : ''}}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Mentor Free Course
              </p>
            </a>
          </li>
          <li class="nav-item d-none">
            <a href="{{ route('discounts.index') }}" class="nav-link {{ request()->is('adm/discounts') ? 'active' : ''}}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Discount
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ route('news.index') }}" class="nav-link {{ request()->is('adm/news') ? 'active' : ''}}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                News
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ route('support.index') }}" class="nav-link {{ request()->is('adm/support') ? 'active' : ''}}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Support Desk
              </p>
            </a>
          </li>
          {{-- <li class="nav-item">
            <a href="{{ route('setting.index') }}" class="nav-link {{ request()->is('adm/setting') ? 'active' : ''}}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Setting
              </p>
            </a>
          </li> --}}
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">@yield('subTitle')</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            @yield('breadcrumb')
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
      @yield('content')
      <!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
    <div class="p-3">
      <h5>Title</h5>
      <p>Sidebar content</p>
    </div>
  </aside>
  <!-- /.control-sidebar -->

  <!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">

    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; {{ date('Y') }} <a href="https://gurusemua.com">gurusemua.com</a>.</strong> All rights reserved.
  </footer>
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->
<script src="{{ asset('plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('dist/js/adminlte.min.js') }}"></script>
@yield('script')

</body>
</html>

resources/views/layouts/certificate-layout.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <!-- CSRF Token -->
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Great+Vibes&display=swap" rel="stylesheet"> 
  <title>Guru Semua Certificate</title>
  @yield('style')
</head>
<body>
  <div id="app">
    <main class="container p-5 justify-content-center d-flex flex-column">
      @yield('content')
    </main>
  </div>
</body>
</html>