routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use App\User;
use \App\Mentor;
use \App\Discount;
/**
 * Main Website ROUTE
 */
Route::get('/', 'LandingPageController@index')->name('landingpage');
Route::post('/search-mentor', 'LandingPageController@searchMentor')->name('search.mentor');
Route::get('/about-us', 'AboutController@index')->name('about-us');
Route::get('/faq', 'AboutController@faqIndex')->name('about-us');
Route::get('/dummy/mentor', 'DummyController@index')->name('dummymentor');
Route::get('/dummy/mentor/show', 'DummyController@view')->name('dummymentorshow');
Route::get('/notification', 'UserController@indexAllNotification')->name('indexAllNotification');
Route::post('/cart/submit-donation', 'CartController@submitDonation')->name('carts.submitDonation');
Route::post('/paymentnotification/handler', 'CartController@notificationHandler')->name('notification.handler');
Route::get('/search', 'LessonController@search')->name('search');
Route::get('/cart', 'CartController@index')->name('indexAllPurchases')->middleware('auth');
Route::get('/faq', 'FaqController@index')->name('faq');
Route::get('/faq/{id}/read', 'FaqController@detail')->name('faq-detail');
Route::get('/privacy-policies', 'SupportDeskController@privacyPolicyPage')->name('privacyPolicies');
Route::get('/privacy-policy/{id}/read', 'SupportDeskController@privacyPolicyDetail')->name('privacyDetail');
Route::get('/terms-and-conditions', 'SupportDeskController@termsAndConditionsPage')->name('termsAndConditions');
Route::get('/terms-and-condition/{id}/read', 'SupportDeskController@termsAndConditionDetail')->name('termsDetail');
Route::resource('news','NewsController')->only(['index', 'showFrontend']);
Route::resource('mentors','MentorController')->only(['index', 'show']);
Route::resource('freecourse','FreecourseController')->only(['show']);
Route::get('/news', 'NewsController@indexFrontend')->name('newsFrontend');
Route::get('/news/{id}/read', 'NewsController@readNewsDetail')->name('readNewsFrontend');
Route::group(['middleware' => 'auth'], function () {
    Route::resource('carts', 'CartController');
    Route::get('/v1/cart/clear-all', 'CartController@clearAll')->name('cart.clearall');
    Route::resource('wishlists', 'WishlistController');
    Route::get('/wishlists/{id}/remove', 'WishlistController@remove')->name('wishlists.remove');
    Route::post('/cart/checkout', 'CartController@checkout')->name('cart.checkout')->middleware('verified');

    Route::post('/transaction-success', function () {
        return view('website.transactionsuccess');
    })->name('cart.finish');
    Route::post('/transaction-pending', function () {
        return view('website.transactionpending');
    })->name('cart.pending');
    Route::post('/transaction-failed', function () {
      return view('website.transactionfailed');
    })->name('cart.failed');;
});
Route::post('news/search', 'NewsController@search')->name('news.search');
Route::get('/certificate', 'UserController@certificate')->name('certificate');
Route::group(['as' => 'main.', 'middleware' => ['auth']], function(){
//    Route::get('/redirect', 'SocialAuthGoogleController@redirect')->name('redirect');
//    Route::get('/home', 'HomeController@index')->name('home');
//    Route::get('/mentors/{mid}/lessons/{lid}', 'LessonController@show')->middleware(['can_watch_lesson']);

//    Route::resource('mentors.lessons','MentorLessonController')->middleware(['can_watch_lesson'])->only(['show']);
//    Route::resource('comments','CommentController');
    Route::post('/mentor/{username}/send-rating', 'MentorController@sendRating')->name('mentor.send-rating');
    Route::post('/lesson/enroll/{username}','LessonController@enroll')->name('comment.enroll');
    Route::get('/profile/{username}', 'UserController@show')->name('user.profile');
    Route::post('/profile/{id}', 'UserController@update')->name('user.profile.update');
    Route::put('/profile/update-password', 'UserController@updatePassword')->name('user.profile.update-password');
    Route::get('/profile/{username}/my-course', 'UserController@myCourses')->name('user.my-courses');
    Route::get('/quiz', function() {
      return view('website.quiz');
    })->name('quiz');
    Route::group(['middleware' => ['auth','can_watch_lesson']], function() {
//        Route::get('/mentors/{mid}/lessons/{lid}', 'LessonController@show');
        Route::resource('mentors.lessons','MentorLessonController')->only(['show'])->middleware('verified');
        Route::get('/mentors/{mentor}/lessons/{lesson}/fetch-comment', 'MentorLessonController@fetchComment')->name('mentors.lessons.fetch-comment');
        Route::post('/mentors/{mentor}/lessons/{lesson}/send-comment', 'MentorLessonController@sendComment')->name('mentors.lessons.send-comment');
        Route::post('/mentors/{mentor}/lessons/{lesson}/edit-comment', 'MentorLessonController@editComment')->name('mentors.lessons.edit-comment');
        Route::post('/mentors/{mentor}/lessons/{lesson}/delete-comment', 'MentorLessonController@deleteComment')->name('mentors.lessons.delete-comment');
        Route::post('/mentors/{mentor}/lessons/{lesson}/finish-watching', 'MentorLessonController@finishWatching')->name('mentors.lessons.finish-watching');
    });

    Route::get('/pay/snaptoken', 'SnapController@token')->name('midtrans.snap');
    Route::post('/pay/payment-summary', 'SnapController@finish')->name('midtrans.finish');
});
Route::post('/pay/notification', 'SnapController@notification');


/**
 * ADMIN ROUTE
*/
Route::group(['prefix' => 'adm', 'middleware' => ['auth','role:admin|mentor|staff']], function(){
    Route::get('/', function() { return redirect()->route('mentors.index'); } );
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::get('/setting', 'SettingController@index')->name('setting.index');
    Route::get('/setting/landingpage', 'SettingController@landingpage')->name('setting.landingpage');
    Route::put('/setting/landingpage', 'SettingController@updateLandingpage')->name('setting.landingpage.update');
    Route::resource('mentors.lessons','MentorLessonController');
    Route::post('/mentors/{username}/lesson/upload-video', 'MentorLessonController@upload')->name('lessons.upload-video');
    Route::group(['middleware' => ['role:admin']],function (){
        Route::resource('users','UserController');
        Route::resource('freecourses','FreecourseController');
        Route::resource('news','NewsController');
        Route::resource('faq', 'FaqController');
        Route::resource('support', 'SupportDeskController');
        Route::resource('discounts','DiscountController');
        Route::get('/discounts/{did}/assign', 'DiscountController@viewAssign')->name('discounts.view-assign');
        Route::post('/discounts/{did}/assign', 'DiscountController@doAssign')->name('discounts.do-assign');

    });
    Route::group(['middleware' => ['role:admin|staff']],function (){
        Route::resource('mentors','MentorController');
        Route::post('/mentors/{mentor}/rearrange', 'MentorController@rearrangeLesson')->name('mentors.rearrange');
        Route::post('/mentors/{mentor}/select-review', 'MentorController@selectReview')->name('mentors.select-review');

        Route::resource('lessons','LessonController');
    });
    Route::group(['middleware' => ['role:admin|mentor']],function (){
        Route::resource('mentors','MentorController')->only(['show', 'edit','update']);
    });
});

/**
 * AUTHENICATION ROUTE
 */
Auth::routes(['verify' => true]);
Route::get('/redirect', 'SocialAuthGoogleController@redirect')->name('redirect');
Route::get('/callback', 'SocialAuthGoogleController@callback')->name('callback');










/*
 * Route Dibawah hanya Untuk kebutuhan Dev Saja
 * Nanti Akan Dihapus.
 * "Ikhsn"
 */

Route::get('/create-new-roles', function() {
    DB::transaction(function () {
        $permission = Permission::create(['name' => 'read comments']);

        $role = Role::create(['name' => 'student']);
        $role->givePermissionTo($permission);
        Role::create(['name' => 'super-admin']);
        Role::create(['name' => 'admin']);
        Role::create(['name' => 'staff']);
        Role::create(['name' => 'mentors']);
    });
});

Route::get('/give-permission-to', function() {
    $role = Role::where('name','super-admin')->first();
    $permission = Permission::all();
    DB::transaction(function () use ($role, $permission){
        $role->givePermissionTo($permission);
    });
});

Route::get('/generate-user',function (){
    DB::beginTransaction();
    try {
        // $permission = Permission::create(['name' => 'read comments']);

        $roleSuperadmin = Role::create(['name' => 'super-admin']);
        $roleAdmin = Role::create(['name' => 'admin']);
        $roleStaff = Role::create(['name' => 'staff']);
        $roleMentor = Role::create(['name' => 'mentor']);
        $roleStudent = Role::create(['name' => 'student']);
        // $roleStudent->givePermissionTo($permission);

        $superadmin = new User([
            'name' => 'super admin',
            'username' => 'superadmin',
            'email' => 'superadmin@gmail.com',
            'password' => bcrypt('password'),
        ]);
        $superadmin->save();
        $superadmin->assignRole($roleSuperadmin);

        $admin = new User([
            'name' => 'first admin',
            'username' => 'firstadmin',
            'email' => 'firstadmin@gmail.com',
            'password' => bcrypt('password'),
        ]);

        $admin->save();
        $admin->assignRole($roleAdmin);

app/Discount.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Discount extends Model
{
    public $price = 0;
    public $percent = 0;

    const DISCOUNT_TYPE_PRICE = 1;
    const DISCOUNT_TYPE_PERCENT = 100;
    public static $rules = [
        'create' =>[
            'code' => 'required|unique:discounts',
            'type' => 'required',
            'desc' => 'required',
            'price' => 'numeric',
            'percent' => 'numeric|max:100',
            'max_price' => 'numeric',
            'discount_date_range' => 'required',
        ],
        'update' =>[
            'code' => 'sometimes|required|unique:discounts',
            'type' => 'required',
            'desc' => 'required',
            'price' => 'numeric',
            'percent' => 'numeric|max:100',
            'max_price' => 'numeric',
            'discount_date_range' => 'required',
        ]
    ];

    public static $type = [1 => 'price', 100 => 'percent'];
    public function mentors(){
        return $this->belongsToMany(Mentor::class,"discount_mentor",'discount_id','mentor_id')->withTimestamps();
    }

    public function setStartedDateAttribute($value){
        $this->attributes['started_dt'] = Carbon::createFromFormat(config('app.datetime_format'), $value)->format('Y-m-d H:i:s');
    }
    public function getStartedDate($value){
        return Carbon::parse($value)->format(config('app.datetime_format'));
    }
    public function setEndedDateAttribute($value){
        $this->attributes['ended_dt'] = Carbon::createFromFormat(config('app.datetime_format'), $value)->format('Y-m-d H:i:s');
    }
    public function getEndedDate($value){
        return Carbon::parse($value)->format(config('app.datetime_format'));
    }

    public function getValueTypeAttribute($value)
    {
        if ($this->type == self::DISCOUNT_TYPE_PRICE) {
            return Helper::IDR($this->value);
        } elseif ($this->type == self::DISCOUNT_TYPE_PERCENT){
            return $this->value . "%";
        }
    }
}

app/Http/Controllers/DiscountController.php
<?php

namespace App\Http\Controllers;

use App\Discount;
use App\Helper;
use App\Mentor;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class DiscountController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $discounts = Discount::all();
        return view('admin.discount.list')
            ->with('discounts',$discounts);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $discount = new Discount();
        return view('admin.discount.create')
            ->with('discount',$discount);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */

    public function store(Request $request){
        $discount = new Discount();
        $this->_save($discount,$request,Discount::$rules['create']);
        return redirect()->route('discounts.index')
            ->with('success', 'Discount is successfully saved');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Discount  $discount
     * @return \Illuminate\Http\Response
     */
    public function show(Discount $discount)
    {
        return view('admin.discount.create')->with('discount',$discount);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Discount  $discount
     * @return \Illuminate\Http\Response
     */
    public function edit(Discount $discount)
    {
        return view('admin.discount.edit')->with('discount',$discount);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Discount  $discount
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Discount $discount)
    {

        $rules = Discount::$rules['update'];
        $rules['code'] .= ',id,' . $discount->id;
        $this->_save($discount,$request,$rules);
        return redirect()->route('discounts.index')->with('success', 'Discount is successfully saved');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Discount  $discount
     * @return \Illuminate\Http\Response
     */
    public function destroy(Discount $discount)
    {
        $discount->delete();
        return redirect()->route('discounts.index')->with('success', 'Discount is successfully remove');
    }

    private function _save($discount,$request,$rules){
        $validatedData = $request->validate($rules);
        $dateRange = explode(' - ',$validatedData['discount_date_range']);
        $discount->code = $validatedData['code'];
        $discount->desc = $validatedData['desc'];
        $discount->type = $validatedData['type'];
        if ($discount->type == Discount::DISCOUNT_TYPE_PRICE){
            $discount->value = $validatedData['price'];
            $discount->max_price = $validatedData['price'];
        } else if ($discount->type == Discount::DISCOUNT_TYPE_PERCENT){
            $discount->value = $validatedData['percent'];
            $discount->max_price = $validatedData['max_price'];
        }
        $discount->is_active = Helper::STATUS_YES;
        $discount->started_at = Helper::formatDate($dateRange[0],config('app.datetime_format'));
        $discount->ended_at = Helper::formatDate($dateRange[1],config('app.datetime_format'));
        DB::transaction(function () use ($discount){
            $discount->save();
            return redirect()->route('discounts.index');
        });
    }

    public function viewAssign($id){
        $discount = Discount::find($id);
        $mentors = Mentor::all();
        return view('admin.discount.assign')
            ->with('discount',$discount)
            ->with('mentors',$mentors);
    }
    public function doAssign(Request $request, $id){
        $validatedData = $request->validate([
            'mentors.*' => 'numeric|exists:mentors,mentor_id'
        ]);
        $discount = Discount::find($id);
        $discount->mentors()->sync($validatedData['mentors']);

        return redirect()->route('discounts.index');
    }
}

resources/views/admin/discount/create.blade.php
@extends('layouts.admin')
@section('title','Lessons')
@section('subTitle','Lesson')
@section('style')
    <!-- Select2 -->
    <link rel="stylesheet" href="{{ asset('plugins/select2/css/select2.min.css') }}">
    <link rel="stylesheet" href="{{ asset('plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('plugins/daterangepicker/daterangepicker.css') }}">

@endsection
@section('breadcrumb')
    <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href="{{ route('discounts.index') }}">Discounts</a></li>
        <li class="breadcrumb-item active">Create Discount</li>
    </ol>
@endsection
@section('content')

    <!-- form start -->
    <form action="{{ route('discounts.store') }}" method="post" >
        @csrf
        <div class="row">
            <div class="col-12">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <h5><i class="fas fa-exclamation-triangle"></i> Error:</h5>
                        <ul class="m-1 pl-3">
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card card-success card-outline">
                    <!-- /.card-header -->
                    <div class="card-body">
                        <div class="form-group">
                            <label for="txtCode">Discount Code</label>
                            <input id="txtCode" type="text" name="code" value="{{ old('code') }}" class="form-control @error('code') is-invalid @enderror" placeholder="Discount Code" >
                            @error('code')
                            <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="txtDesc">Description</label>
                            <textarea name="desc" id="txtDesc" rows="3" class="form-control @error('desc') is-invalid @enderror">{{ old('desc') }}</textarea>
                            @error('desc')
                            <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="selType">Type</label>
                            <select name="type" class="form-control select2bs4 @error('type') is-invalid @enderror" id="selType" style="width: 100%;" >
                                @php $type = [1 => 'Price', 100 => 'Percent'] @endphp
                                @foreach ($type as $key => $val)
                                    @if (old('type') == $key)
                                        <option value="{{ $key }}" selected>{{ $val }}</option>
                                    @else
                                        <option value="{{ $key }}">{{ $val }}</option>
                                    @endif
                                @endforeach
                            </select>
                            @error('type')
                            <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                            @enderror
                        </div>
                        <div class="form-group" style="display: none">
                            <label for="txtPrice">Price</label>
                            <input id="txtPrice" type="number" name="price" value="{{ old('price',$discount->price) }}" class="form-control @error('price') is-invalid @enderror" placeholder="Price" >
                            @error('price')
                            <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                            @enderror
                        </div>
                        <div class="form-group" style="display: none">
                            <label for="txtPercent">Percent</label>
                            <input id="txtPercent" type="number" name="percent" value="{{ old('percent',$discount->percent) }}" class="form-control @error('percent') is-invalid @enderror" placeholder="Percent" >
                            @error('percent')
                            <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                            @enderror
                        </div>
                        <div class="form-group" style="display: none">
                            <label for="txtMaxPrice">Maximum Discount Price</label>
                            <input id="txtMaxPrice" type="number" name="max_price" value="{{ old('max_price',0) }}" class="form-control @error('max_price') is-invalid @enderror" placeholder="Enter Title" >
                            @error('max_price')
                            <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                            @enderror
                        </div>

                        <!-- Date and time range -->
                        <div class="form-group">
                            <label>Date and time range:</label>

                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="far fa-clock"></i></span>
                                </div>
                                <input type="text" name="discount_date_range" class="form-control float-right" id="txtDiscountDateRange">
                            </div>
                            <!-- /.input group -->
                        </div>

                    </div>
                    <!-- /.card-body -->

                </div>
            </div>
        </div>
        <div class="row ">
            <div class="col-12 mb-3">
                <input type="reset" value="Reset" class="btn btn-success">
                <input type="submit" value="Save" class="btn btn-success">
            </div>
        </div>
    </form>
@endsection

@section('script')
<!-- Select2 -->
<script src="{{ asset('plugins/select2/js/select2.full.min.js') }}"></script>
<script src="{{ asset('plugins/moment/moment.min.js') }}"></script>
<script src="{{ asset('plugins/daterangepicker/daterangepicker.js') }}"></script>

<script>

    $('input[type="file"]').change(function(e){
        var fileName = e.target.files[0].name;
        $(this).closest('.form-group').find('.custom-file-label').html(fileName);
    });

    $('.select2bs4').select2({
        theme: 'bootstrap4'
    });

    //Date range picker with time picker
    $('#txtDiscountDateRange').daterangepicker({
        timePicker: true,
        timePickerIncrement: 15,
        timePicker24Hour: true,
        timePickerSeconds:true,
        drops:'up',
        locale: {
            format: '{{ config('app.datetime_format_js') }}'
        }
    });

    $('#selType').change(function () {
        let selectedValue = $(this).val();
        $('#txtPercent').parent().hide();
        $('#txtMaxPrice').parent().hide();
        $('#txtPrice').parent().hide();
        if (selectedValue == 1){
            $('#txtPrice').parent().show();
        } else if (selectedValue == 100) {
             $('#txtPercent').parent().show();
            $('#txtMaxPrice').parent().show();
        }
    });
    function convertToSlug(Text)
    {
        return Text
            .toLowerCase()
            .replace(/[^\w ]+/g,'')
            .replace(/ +/g,'-')
            ;
    }
    $('#selType').trigger('change');

</script>
@endsection

resources/views/admin/discount/list.blade.php
@extends('layouts.admin')
@section('title','Discounts')
@section('subTitle','Discounts')
@section('style')
    <!-- DataTables -->
    <link rel="stylesheet" href="../../plugins/datatables-bs4/css/dataTables.bootstrap4.css">
@endsection
@section('breadcrumb')
    <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item active">Discounts</li>
    </ol>
@endsection
@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="row mb-2 mb-md-3">
                        <div class="col-12 d-flex justify-content-between">
                            <div class="left"></div>
                            <div class="right">
                                <a class="btn btn-success btn-sm" href="{{ route('discounts.create') }}"> Create Discount</a>
                            </div>
                        </div>
                    </div>
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <table id="dt1" class="table table-bordered table-hover dt-responsive" width="100%">
                        <thead>
                            <tr>
                                <th>Discount Code</th>
                                <th>Type</th>
                                <th>Value</th>
                                <th>Max Price</th>
                                <th>Started At</th>
                                <th>Ended At</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach($discounts as $discount)
                            <tr>
                                <td>
                                    <span class="d-inline-block bg-{{ $discount->is_active ? 'success' : 'danger' }} mr-1"
                                          style="height: .7em; width: .7em; border-radius: 99px">
                                    </span>
                                    {{ $discount->code }}
                                </td>
                                <td>{{ \App\Discount::$type[$discount->type] }}</td>
                                <td>
                                    {{ $discount->value_type }}
                                </td>
                                <td>{{ \App\Helper::IDR($discount->max_price) }}</td>
                                <td>{{ $discount->started_at }}</td>
                                <td>{{ $discount->ended_at }}</td>
                                <td>
                                    <form action="{{ route('discounts.destroy',$discount->id) }}" method="POST" style="text-align: right;">
                                        <a title="Edit Discount" href="{{ route('discounts.edit',$discount->id) }}" class="btn btn-link text-info">
                                            <ion-icon name="create-outline"></ion-icon>
                                        </a>
                                        <a title="Assign Discount" href="{{ route('discounts.view-assign',$discount->id) }}" class="btn btn-link text-success">
                                            <ion-icon name="people-outline"></ion-icon>
                                        </a>
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-link text-danger">
                                            <ion-icon name="trash-outline"></ion-icon>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
<!-- DataTables -->
<script src="{{ asset('plugins/datatables/jquery.dataTables.js') }}"></script>
<script src="{{ asset('plugins/datatables-bs4/js/dataTables.bootstrap4.js') }}"></script>
<script>

    $(function () {
        $('#dt1').DataTable({
            "scrollX": true
        });
    });

</script>
@endsection